config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create destroy]
  # ログイン関連
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # # リスト関連
  resources :list, only: %i[index new create edit update destroy] do
    resources :card, only: %i[new create show edit update destroy]
  end

  # React化に伴い、ListとCardのルーティングを下記のように変更
  resources :cards, only: [:index, :create, :update, :destroy] do
    post :update_all_position, on: :collection
  end

  resources :lists, only: [:index, :create, :destroy] do
    delete :destroy_all_cards, on: :member
  end

  # linebot
  post '/callback', to: 'reminders#callback'

  # Lineログイン・認証
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # プロフィール
  resource :profile, only: %i[show edit update]

  # パスワードリセット
  resources :password_resets, only: %i[create edit update new]

  # ポモドーロタイマー
  resources :pomodoro_sessions, only: [:create, :index] do
    collection do
      get 'count'
    end
  end

  #プライバシーポリシーと利用規約
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  # お問い合わせページ
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('profiles.edit.success')
    else
      render :edit
    end
  end

  private
  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :user_name, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1 class="text-center my-5 font-japanese"><%= t('.title') %></h1>
      <%= form_with model: @user, url: profile_path, method: :put do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3 font-japanese">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3 font-japanese">
          <%= f.label :user_name, class: "form-label" %>
          <%= f.text_field :user_name, class: "form-control" %>
        </div>
        <div class="mb-3 font-japanese">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, class: 'form-control mb-3', accept: 'image/*' %>
          <%= f.hidden_field :avatar_cache %>
          <div class='mt-5 mb-3 text-center'>
            <%= image_tag @user.avatar.url,
                          class: 'rounded-circle',
                          id: 'preview',
                          size: '100x100' %>
          </div>
        </div>
        <div class="text-center">
          <%= f.submit class: "btn-custom" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1 class="text-center my-5 font-japanese"><%= t('.title') %></h1>
      <table class="table table-bordered rounded" style="background-color: #EBE9DF;">
        <tbody>
          <tr>
            <th scope="row" style="background-color: #EBE9DF;"><%= User.human_attribute_name(:email) %></th>
            <td style="background-color: #EBE9DF;"><%= current_user.email %></td>
          </tr>
          <tr>
            <th scope="row" style="background-color: #EBE9DF;"><%= User.human_attribute_name(:full_name) %></th>
            <td style="background-color: #EBE9DF;"><%= current_user.user_name %></td>
          </tr>
          <tr>
            <th scope="row" style="background-color: #EBE9DF;"><%= User.human_attribute_name(:avatar) %></th>
            <td style="background-color: #EBE9DF;"><%= image_tag current_user.avatar_url, class: 'rounded-circle', size: '50x50' %></td>
          </tr>
        </tbody>
      </table>
      <div class="d-flex justify-content-between mt-4">
        <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success' %>
        <%= link_to 'アカウント削除', user_path(current_user), data: { turbo: true, turbo_method: :delete, turbo_confirm: t('users.destroy.confirm')}, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>