config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create destroy]
  # ログイン関連
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # # リスト関連
  resources :list, only: %i[index new create edit update destroy] do
    resources :card, only: %i[new create show edit update destroy]
  end

  # React化に伴い、ListとCardのルーティングを下記のように変更
  resources :cards, only: [:index, :create, :update, :destroy] do
    post :update_all_position, on: :collection
  end

  resources :lists, only: [:index, :create, :destroy] do
    delete :destroy_all_cards, on: :member
  end

  # linebot
  post '/callback', to: 'reminders#callback'

  # Lineログイン・認証
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # プロフィール
  resource :profile, only: %i[show edit update]

  # パスワードリセット
  resources :password_resets, only: %i[create edit update new]

  # ポモドーロタイマー
  resources :pomodoro_sessions, only: [:create, :index] do
    collection do
      get 'count'
    end
  end

  #プライバシーポリシーと利用規約
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  # お問い合わせページ
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
end

app/views/shared/_before_login_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Home", root_path, id: "logo", class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <!-- デスクトップサイズ向けのドロップダウンメニュー -->
        <li class="nav-item dropdown d-none d-lg-block">
          <a class="nav-link" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user fa-lg me-2"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <%= link_to t('header.login'), login_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to t('header.terms_of_service'), terms_of_service_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to t('header.privacy_policy'), privacy_policy_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to t('contact.title'), new_contact_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
        <!-- モバイルサイズ向けの通常リンク（ハンバーガーメニュー内） -->
        <li class="nav-item d-lg-none">
          <%= link_to t('header.login'), login_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('header.terms_of_service'), terms_of_service_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('header.privacy_policy'), privacy_policy_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('contact.title'), new_contact_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "QuoteTodo", root_path, id: "logo", class: "navbar-brand font-english" %>
    <button class="navbar-toggler d-lg-none common-menu-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <!-- 大きい画面ではアバター画像を表示 -->
        <li class="nav-item dropdown d-none d-lg-block">
          <%= link_to '#', class: 'common-menu-toggle', id: 'navbarDropdownMenuLink', role: 'button', data: { bs_toggle: 'dropdown' }, aria: { expanded: 'false' } do %>
            <%= image_tag(current_user.avatar.url || 'images/sample.jpg', alt: 'Avatar', class: 'rounded-circle mr15', width: '40', height: '40') %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to t('header.profile'), profile_path, data: { turbo: true }, class: "dropdown-item" %></li>
            <li><%= link_to t('header.terms_of_service'), terms_of_service_path, data: { turbo: true }, class: "dropdown-item" %></li>
            <li><%= link_to t('header.privacy_policy'), privacy_policy_path, data: { turbo: true }, class: "dropdown-item" %></li>
            <li><%= link_to t('contact.title'), new_contact_path, data: { turbo: true }, class: "dropdown-item" %></li>
            <li><%= link_to t('header.logout'), logout_path, data: { turbo: true, turbo_method: :delete }, class: "dropdown-item" %></li>
          </ul>
        </li>
        <!-- モバイルサイズ向けの通常リンク（ハンバーガーメニュー内） -->
        <li class="nav-item d-lg-none">
          <%= link_to t('header.profile'), profile_path, data: { turbo: true }, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('header.terms_of_service'), terms_of_service_path, data: { turbo: true }, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('header.privacy_policy'), privacy_policy_path, data: { turbo: true }, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('contact.title'), new_contact_path, data: { turbo: true }, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to t('header.logout'), logout_path, data: { turbo: true, turbo_method: :delete }, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</header>