config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create destroy]
  # ログイン関連
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # # リスト関連
  resources :list, only: %i[index new create edit update destroy] do
    resources :card, only: %i[new create show edit update destroy]
  end

  # React化に伴い、ListとCardのルーティングを下記のように変更
  resources :cards, only: [:index, :create, :update, :destroy] do
    post :update_all_position, on: :collection
  end

  resources :lists, only: [:index, :create, :destroy] do
    delete :destroy_all_cards, on: :member
  end

  # linebot
  post '/callback', to: 'reminders#callback'

  # Lineログイン・認証
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # プロフィール
  resource :profile, only: %i[show edit update]

  # パスワードリセット
  resources :password_resets, only: %i[create edit update new]

  # ポモドーロタイマー
  resources :pomodoro_sessions, only: [:create, :index] do
    collection do
      get 'count'
    end
  end

  #プライバシーポリシーと利用規約
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  # お問い合わせページ
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i[edit update destroy]
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end

  def edit; end

  def update
    if @list.update(list_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to list_index_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:title).merge(user:current_user)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ActionController::API
  def index
    lists = current_user.lists.all.order(created_at: :asc)
    render json: lists.as_json(only: [:id, :title])
  end

  def create
    list = current_user.lists.new(list_params)
    if list.save
      render json: { message: '保存が成功しました', list: list.as_json(only: [:id, :title]) }, status: :ok
    else
      render json: { error: '保存に失敗しました' }, status: :unprocessable_entity
    end
  end

  def destroy
    list = List.find(params[:id])
    if list.destroy
      render json: { message: '削除が成功しました' }, status: :ok
    else
      render json: { error: '削除に失敗しました' }, status: :unprocessable_entity
    end
  end

  def destroy_all_cards
    list = List.find(params[:id])

    if destroy_cards(list.cards)
      render json: { message: '削除が成功しました' }, status: :ok
    else
      render json: { error: '削除に失敗しました' }, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

  def destroy_cards(cards)
    Card.transaction do
      cards.each do |card_data|
        card = Card.find(card_data['id'])
        card.destroy!
      end
    rescue => e
      Rails.logger.error "Failed to destroy cards: #{e.message}"
      return false
    end
    true
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/list/index.html copy.erb
<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to list_path(list), data: { turbo_method: :delete, turbo_confirm: "削除しますか？"}, class: 'btn btn-outline-secondary' do %>
              <i class="fas fa-trash"></i>
            <% end %>
            <%= link_to edit_list_path(list), class: 'btn btn-outline-secondary' do %>
              <i class="fas fa-pen"></i>
            <% end %> 
          </div>
        </div>
        <div class="cardWrapper">
          <% list.cards.each do |card| %>
            <%= link_to list_card_path(list, card), class:"cardDetail_link" do %>
              <div class="card">
                <h3 class="card_title"><%= card.title %></h3>
                <%= card.due_date %>
                <% if card.memo.size > 0 %>
                  <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <div class="addCard">
            <%= link_to new_list_card_path(list), class:"addCard_link" do %>
              <i class="far fa-plus-square"></i>
            <% end %>
            さらにカードを追加
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/list/index.html.erb
<div class="flex h-[93%] flex-col bg-base-200" id="todo_app"></div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: list_index_path, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>

      <div class="mb-3">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      </div>
      <div class="text-center">
        <%= f.submit "作成", class: "btn btn-primary submitBtn" %>
      </div>
    <% end %>
  </div>
</div>