config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create destroy]
  # ログイン関連
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # # リスト関連
  resources :list, only: %i[index new create edit update destroy] do
    resources :card, only: %i[new create show edit update destroy]
  end

  # React化に伴い、ListとCardのルーティングを下記のように変更
  resources :cards, only: [:index, :create, :update, :destroy] do
    post :update_all_position, on: :collection
  end

  resources :lists, only: [:index, :create, :destroy] do
    delete :destroy_all_cards, on: :member
  end

  # linebot
  post '/callback', to: 'reminders#callback'

  # Lineログイン・認証
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # プロフィール
  resource :profile, only: %i[show edit update]

  # パスワードリセット
  resources :password_resets, only: %i[create edit update new]

  # ポモドーロタイマー
  resources :pomodoro_sessions, only: [:create, :index] do
    collection do
      get 'count'
    end
  end

  #プライバシーポリシーと利用規約
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  # お問い合わせページ
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('user_sessions.destroy.success')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1 class="text-center my-5 font-japanese"><%= t('user_sessions.new.title') %></h1>
      <div class="d-flex justify-content-center my-2">
        <%= link_to image_tag('btn_login_base.png', alt: t('top.login_with_line')), auth_at_provider_path(provider: :line), class: "line-login" %>
      </div>
      <%= form_with url: login_path do |f| %>
        <div class="my-3 font-japanese">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="my-3 font-japanese">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="text-center my-3">
          <%= f.submit t('user_sessions.new.login'), class: "btn-custom" %>
        </div>
      <% end %>
      <div class='d-flex justify-content-between'>
        <%= link_to t('user_sessions.new.to_register_page'), new_user_path, class: 'text-link' %>
        <%= link_to t('user_sessions.new.password_forget'), new_password_reset_path, class: 'text-link' %>
      </div>
    </div>
  </div>
</div>